name: Deploy ADF ARM to PROD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-adf:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Azure Login (Service Principal via JSON)
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy ARM template to PROD ADF
      uses: azure/arm-deploy@v2
      with:
        scope: resourcegroup
        resourceGroupName: rg-adf-dev-prod
        region: southindia
        template: adf_publish/ARMTemplateForFactory.json
        parameters: adf_publish/ARMTemplateParametersForFactory.json
        deploymentMode: Incremental
