name: Deploy ADF ARM to PROD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-adf:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main
      uses: actions/checkout@v4

    - name: Checkout adf-dev-pipelines branch
      uses: actions/checkout@v4
      with:
        ref: adf-dev-pipelines
        path: adf-dev-pipelines

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy ARM template
      uses: azure/arm-deploy@v2
      with:
        scope: resourcegroup
        resourceGroupName: rg-adf-dev-prod
        region: southindia
        template: adf-dev-pipelines/ARMTemplateForFactory.json
        parameters: adf-dev-pipelines/ARMTemplateParametersForFactory.json
        deploymentMode: Incremental
